version: '3.5'
services:
  lifx-scene-forwarder:
    container_name: lifx-scene-forwarder
    image: yenba/lifx-scene-forwarder
    ports:
      - 8088:80
    volumes:
      - ./config:/app/config
    restart: unless-stopped
